import { Toaster } from "react-hot-toast";
import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./redux/provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Login-Admin Dashboard App",
  description: "Generated by Ha3er JS app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children} <Toaster position="top-right" />
        </Providers>
      </body>
    </html>
  );
}
